# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            Data & Design
tagline:          'Data & Design'
description:      'HCI Special Interest Group on Data as Human-Centred Design Material'
url:              http://datacentricdesign.com
baseurl:          /

paginate:         5
