# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Data-Centric Design
tagline:          'Data-Centric Design'
description:      'HCI Special Interest Group on Data as Human-Centred Design Material'
url:              http://datacentricdesign.com
baseurl:          /

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/datacentricdesign/sig
